name: test_chat_application
description: A real-time Flutter chat app with Firebase Auth, Firestore, and Clean Architecture.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.0.3
  dartz: ^0.10.1
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  google_fonts: ^6.2.1
  intl: ^0.20.2
  go_router: ^17.3.0
  toastification: ^3.2.0
  flutter_secure_storage: ^10.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4


flutter:
  uses-material-design: true
